13 feature admin interface page stub
2022-CITS3200-GraphTeam/CITS3200-GroupProject pull request #22
Opened 2022-09-02 02:41 UTC by LKBEAST

- Page stub created admin interface.
- Added gitignore

2022-09-02 03:14 UTC, met4000 requested changes

2022-09-02 03:14 UTC, met4000 commented on templates/admin_interface.html
> +          console.log(dd)
missing semicolon

2022-09-02 03:14 UTC, met4000 commented on templates/admin_interface.html
> +          console.log('hi');
should this still be here?

2022-09-02 03:14 UTC, met4000 commented on templates/admin_interface.html
> +    <ul style="    list-style-type: none;
should css styles be done through classes and in a separate file?

2022-09-13 19:08 UTC, LKBEAST commented on templates/admin_interface.html
> +    <ul style="    list-style-type: none;
Fixed the changes

2022-09-13 19:10 UTC, LKBEAST reviewed
Basically I fixed all the issues

I moved the styling into the css

I moved the javascript into the js file

I added my graph and my header to Wayne's design so we can also get rid of those tickets.

2022-09-14 06:58 UTC, met4000 submitted a review, later dismissed

2022-09-14 14:31 UTC, met4000 approved these changes

2022-09-14 14:34 UTC, merged