Added generating graph based on initial input
2022-CITS3200-GraphTeam/CITS3200-GroupProject pull request #52
Opened 2022-09-20 15:39 UTC by LKBEAST

~~Only works for initial graph generation, needs to be updatable but thats a different ticket.~~ (edit: fixed now) I have renamed some variables maybe we change them back but the new names are more clear.

Closes #42, closes #43, and closes #53.

2022-09-23 07:08 UTC, met4000 requested changes

2022-09-23 07:08 UTC, met4000 commented on components/graph_data_types/Potato.mjs
> +let a = new GraphDataObject();
I think this was a temp file; it can probably get removed

2022-09-27 07:08 UTC, met4000 commented
Is the PR description still accurate (i.e. it only works once when the graph is initially generated), or does this include the fix for #53 ?

2022-09-27 07:54 UTC, met4000 approved these changes

2022-09-27 07:55 UTC, merged

2022-09-27 07:55 UTC, LKBEAST commented
Adds all the changes we need.