Added  drag functionality
2022-CITS3200-GraphTeam/CITS3200-GroupProject pull request #64
Opened 2022-09-28 02:26 UTC by LKBEAST

Added drag functionality

2022-09-28 03:15 UTC, met4000 requested changes

2022-09-28 03:15 UTC, met4000 commented on components/admin_interface_main/main.js
> +    document.getElementsByClassName("nameInput")[index].value = name;
Can probably remove the assignment to the column name (just in case that messes something up)

2022-09-28 13:43 UTC, LKBEAST commented on components/admin_interface_main/main.js
> +    document.getElementsByClassName("nameInput")[index].value = name;
done

2022-09-28 14:06 UTC, met4000 approved these changes

2022-10-05 03:06 UTC, met4000 requested changes

2022-10-05 03:06 UTC, met4000 commented on components/participant_interface_main/participant_interface.js
> +let myChart;
can you undo this change

2022-10-05 03:15 UTC, met4000 approved these changes

2022-10-05 03:16 UTC, merged