24 feature participant interface page styling + layout
2022-CITS3200-GraphTeam/CITS3200-GroupProject pull request #92
Opened 2022-10-09 12:00 UTC by DannaTB

TODO: review ok button from help modal - requested styling completed

2022-10-09 13:31 UTC, met4000 requested changes

2022-10-09 13:31 UTC, met4000 commented on templates/participant_interface.html
> +      <input type="number" min="0" id="integerValue" class="form-control" oninput="updateSection()"> <br /> <br>
I think `oninput="updateSection()"` got changed by another PR and isn't used now; I'm getting an "updateSection is not defined" error when the input is adjusted.

2022-10-09 13:31 UTC, met4000 commented on templates/test.html
> +</html>
I think this might be a temp or test file; not sure if this is meant to be merged in or not

2022-10-09 13:33 UTC, met4000 commented on templates/participant_interface.html
> +      <input type="number" min="0" id="integerValue" class="form-control" oninput="updateSection()"> <br /> <br>
(i.e. I think it got removed on the original dev branch, but because the changes to the CSS involved shifting stuff around git didn't realise it should've been removed here too)

2022-10-10 02:18 UTC, DannaTB commented on templates/test.html
> +</html>
This has been deleted

2022-10-10 02:19 UTC, DannaTB commented on templates/participant_interface.html
> +      <input type="number" min="0" id="integerValue" class="form-control" oninput="updateSection()"> <br /> <br>
This has been removed

2022-10-10 02:21 UTC, met4000 approved these changes

2022-10-10 02:21 UTC, merged