75 admin interface editing popup
2022-CITS3200-GraphTeam/CITS3200-GroupProject pull request #93
Opened 2022-10-09 12:11 UTC by LKBEAST

I decided to keep the step functionality in this branch as Blake's branch won't be ready for tomorrows meeting. Want to show as much functionality as we can.

2022-10-09 14:09 UTC, met4000 requested changes

2022-10-09 14:09 UTC, met4000 commented on components/admin_interface_main/main.js
> +}*/
Should this be removed, instead of commented out (to make the code cleaner)?

2022-10-09 14:09 UTC, met4000 commented on components/participant_interface_main/graph_handlers.mjs
> +  // TODO @lachy
Could remove TODO line

2022-10-09 14:09 UTC, met4000 commented on templates/admin_interface.html
> +      <li><button id="parModalButton" type="button" class="btn btn-light" onclick="openModal('participantModal')"> Edit Help Message </button> </li>
We probably need to ask the client what they think it should be called and/or where the button should be, but something like "Edit _Participant_ Help Message" might make it clearer that it isn't e.g. the _admin_ help message that is being edited.

2022-10-09 14:09 UTC, met4000 commented on templates/admin_interface.html
> +  <header> <Strong> Tutorial</Strong></header>
I think a title more similar to e.g. what's on the button to open the modal ("Edit Help Message", or whatever it ends up being) might be more intuitive to users.

2022-10-09 14:09 UTC, met4000 commented on templates/participant_interface.html
> +      <strong>Tutorial</strong>
Should we also pass through a custom title? (idk - just something I thought of then)

2022-10-10 02:09 UTC, LKBEAST commented on templates/participant_interface.html
> +      <strong>Tutorial</strong>
maybe ask him in the meeting

2022-10-10 02:30 UTC, met4000 submitted a review, later dismissed

2022-10-10 02:32 UTC, met4000 approved these changes

2022-10-10 02:32 UTC, merged